### ISSUE TITLE
why do u need chatid

### ISSUE THREAD

**Issue by jjhesk** [hexoul/ether-stealer#1]
where is the telegram module?

**Comment by hexoul** [comment]
> why do u need chatid

Telegram `chatid` will be used to notify you when account mining is done, though the option is optional. If not set, you can check the messages according to log module setting. stdout or file.

> where is the telegram module?

Please check [here](https://github.com/hexoul/ether-stealer/blob/master/log/log.go#L50-L56). As it uses open API, there is no additional module or code in this repository.
